version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P4SSW@RD"
    ports:
      - "1433:1433"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
volumes:
  mssql-server-linux-data: